# External Gems
gems: 						[octopress-paginate]

# Site Settings
baseurl: 	  	"http://lndscape.com"
title: 			  Lndscape

name: 			  Lndscape
description: 	A vida é uma aventura que deve ser compartilhada.
url: 			    "http://www.lndscape.com"

paginate: 		  5
paginate_path: 	"blog/page:num"

twitter: 		lndscape
email: 			contact.lndscape@gmail.com

disqus: 		  landscape-1
analytics: 		UA-86042564-1

copyright: 		Copyright 2016 Lndscape.

# Build Settings
markdown: 					kramdown
permalink: 					pretty
highlighter:        rouge
